name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  deploy-builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u jessekramer --password-stdin

      - name: Build and deploy images
        run: ./build-and-release.sh --release
