name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-builds:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - name: Build images
        run: ./build-and-release.sh

  deploy-builds:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u jessekramer --password-stdin

      - name: Build and deploy images
        run: ./build-and-release.sh --release
