name: Test Build

on:
  pull_request:

jobs:
  test-builds:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - name: Build images
        run: ./build-and-release.sh
